pipeline {
    agent any 
    environment {
        IMAGE_TAG = "(BUILD_NUMBER)"
    }
    stages {

        stage ( 'Build docker'  ){
            steps {
                script {
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t abhishekf5/cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }
        stage ('Push the artifacts to docker hub') {
            steps {
                script {
                    sh '''
                    echo 'Push to Repo'
                    docker push ramesh95/ultimate-cicd:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
}