pipeline {
    agent None 
    stages {
        stage ( 'Backend' ) {
            agent {
                docker  {image 'maven:3.8.1-adoptopenjdk-11'}
            }
            steps {
            sh 'mvn --version'
            echo '1234'   
            }
        }
        stage ( 'Front_end' ) {
            agent {
                docker {image 'node:16-alpine'}

            }
            steps {
                sh 'node --version'
            }
        }
    }
}
