pipeline {
    agent any 
    stages {
        stage ( 'Backend' ) {
            agent {
                docker  {image 'maven:3.8.1-adoptopenjdk-11'}
            }
            steps {
            sh 'mvn --version'
            }
         }
        stage ( 'Front_end' ) {
            agent {
                docker {image 'node:16-alpine'}

            }
            steps {
                sh 'node --version'
            }
        }
        stage ( 'Execute the commands' ) {
            agent { 
                docker {image 'node:16-alpine'}
            }
            steps {
                echo "11111"
            }
            }
    }
}
