pipeline {
  agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }
  stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/Iam-Marichamy/Jenkins_Projects.git'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package'
      }
    }
    stage('Static Code Analysis') {
            environment {
                SONAR_URL = "http://13.50.112.223:9000"
            }
            steps {
                script {
                    // 1. Fetch the exact download path of your scanner installation 
                    def scannerHome = tool name: 'sonar-scanner-5', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
                    
                    withCredentials([string(credentialsId: 'SonarQube', variable: 'SONAR_AUTH_TOKEN')]) {
                        // 2. Used double quotes ("") and explicitly ran it from ${scannerHome}/bin/
                        // 3. Escaped \$SONAR_AUTH_TOKEN so the shell handles the variable cleanly
                        sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
                      }
                    }
                }
          }
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "ramesh95/ultimate-cicd:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "java-maven-sonar-argocd-helm-k8s/spring-boot-app/Dockerfile"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
      steps {
        script {
            sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                dockerImage.push()
            }
        }
      }
    }
    stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "Jenkins_Projects"
            GIT_USER_NAME = "iam-Marichamy"
        }
        steps {
            withCredentials([string(credentialsId: 'java_pipe', variable: 'GITHUB_TOKEN')]) {
                sh '''
                    git config user.email "ramkarnan95@gmail.com"
                    git config user.name "Iam-Marichamy"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
                    git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
                   # Only commit if there are staged differences
                    if ! git diff --cached --quiet; then
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                    # git push commands here...
                    else
                    echo "No changes detected in deployment.yml. Skipping commit."
                    fi
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:master
                '''
            }
        }
    }
  }
}
