pipeline {
  agent {
    docker {image 'node:16-alpine'}
  }
  stages {
    stage ( 'Test1' ) {
      steps {
        sh 'node --version'
      }
      steps {
        echo 1234
      }
      steps {
        echo "I have sucessfully automated"
  }
}

