pipeline {
  agent {
    docker { image 'node:16-alpine'
           args ''  // No registry needed
           }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
